---
title: "EPT Results"
author: "Emily Pollock"
date: "4/15/2021"
output: 
  html_document:
    code_folding: hide
---

```{r s, include=FALSE}
#knitr::opts_chunk$set(echo = TRUE)
library(here)
library(kableExtra)
library(tidyverse)
source(here("functions", "analyze_sims.R"))
s1 <- readRDS(here("sims", "fem.mod", "simBase.rds"))
s2 <- readRDS(here("sims", "fem.mod", "simAvg.rds"))
s3 <- readRDS(here("sims", "fem.mod", "simNc.rds"))
s1ept <- readRDS(here("sims", "fem.mod", "simBaseEPT.rds"))
s2ept <- readRDS(here("sims", "fem.mod", "simAvgEPT.rds"))
s3ept <- readRDS(here("sims", "fem.mod", "simNcEPT.rds"))
```
# Reinfection

## Females
```{r reinfs-female}
dat <- reinf(s1, start = 1500)
dat2 <- reinf(s2, start = 1500)
dat3 <- reinf(s3, start = 1500)

datept <- reinf(s1ept, start = 1500)
dat2ept <- reinf(s2ept, start = 1500)
dat3ept <- reinf(s3ept, start = 1500)

## Any Reinfection
r <- data.frame(`M/F Concurrency` = dat[[1]][1:3], 
               `Avg Concurrency` = dat2[[1]][1:3],
               `No Concurrency` = dat3[[1]][1:3])
r$Treatment <- rep("Low Partner Treatment")

r2 <- data.frame(`M/F Concurrency` = datept[[1]][1:3], 
               `Avg Concurrency` = dat2ept[[1]][1:3],
               `No Concurrency` = dat3ept[[1]][1:3])
r2$Treatment <- rep("Incresed Partner Treatment")

rfull <- rbind(r, r2)

rfull$Reinfection <- factor(rep(c("Twelve", "Six", "Three"),2), levels = c("Three", "Six", "Twelve"))
rfull$ReinfType <- rep("Any",6)

## Reinfection Following Diagnosis

d <- data.frame(`M/F Concurrency` = dat[[1]][4:6], 
               `Avg Concurrency` = dat2[[1]][4:6],
               `No Concurrency` = dat3[[1]][4:6])
d$Treatment <- rep("Low Partner Treatment")

d2 <- data.frame(`M/F Concurrency` = datept[[1]][4:6], 
               `Avg Concurrency` = dat2ept[[1]][4:6],
               `No Concurrency` = dat3ept[[1]][4:6])
d2$Treatment <- rep("Incresed Partner Treatment")

dfull <- rbind(d, d2)


dfull$Reinfection <- factor(rep(c("Twelve", "Six", "Three"),2), levels = c("Three", "Six", "Twelve"))
dfull$ReinfType <- rep("Following Diagnosis",6)

full <- rbind(rfull,dfull)
full <- full %>% pivot_longer(cols=colnames(full[1:3]), names_to = "Behavior")

full %>% ggplot(aes(x=Reinfection, y=value, col=Treatment)) +
  geom_point(aes(shape=ReinfType), size=3) +
  facet_wrap("Behavior")
```

## Males
```{r reinfs-male}
## Any Reinfection
r <- data.frame(`M/F Concurrency` = dat[[1]][7:9], 
               `Avg Concurrency` = dat2[[1]][7:9],
               `No Concurrency` = dat3[[1]][7:9])
r$Treatment <- rep("Low Partner Treatment")

r2 <- data.frame(`M/F Concurrency` = datept[[1]][7:9], 
               `Avg Concurrency` = dat2ept[[1]][7:9],
               `No Concurrency` = dat3ept[[1]][7:9])
r2$Treatment <- rep("Incresed Partner Treatment")

rfull <- rbind(r, r2)

rfull$Reinfection <- factor(rep(c("Twelve", "Six", "Three"),2), levels = c("Three", "Six", "Twelve"))
rfull$ReinfType <- rep("Any",6)

## Reinfection Following Diagnosis

d <- data.frame(`M/F Concurrency` = dat[[1]][10:12], 
               `Avg Concurrency` = dat2[[1]][10:12],
               `No Concurrency` = dat3[[1]][10:12])
d$Treatment <- rep("Low Partner Treatment")

d2 <- data.frame(`M/F Concurrency` = datept[[1]][10:12], 
               `Avg Concurrency` = dat2ept[[1]][10:12],
               `No Concurrency` = dat3ept[[1]][10:12])
d2$Treatment <- rep("Incresed Partner Treatment")

dfull <- rbind(d, d2)


dfull$Reinfection <- factor(rep(c("Twelve", "Six", "Three"),2), levels = c("Three", "Six", "Twelve"))
dfull$ReinfType <- rep("Following Diagnosis",6)

full <- rbind(rfull,dfull)
full <- full %>% pivot_longer(cols=colnames(full[1:3]), names_to = "Behavior")

full %>% ggplot(aes(x=Reinfection, y=value, col=Treatment)) +
  geom_point(aes(shape=ReinfType), size=3) +
  facet_wrap("Behavior")
```

# Incidence 
```{r incid-female}
dat <- irate(s1, start = 1500)
dat2 <- irate(s2, start = 1500)
dat3 <- irate(s3, start = 1500)
datept <- irate(s1ept, start = 1500)
dat2ept <- irate(s2ept, start = 1500)
dat3ept <- irate(s3ept, start = 1500)

i.fem.s1 <- dat[[1]][1:6]
i.male.s1 <- dat[[1]][7:12]
i.fem.s2 <- dat2[[1]][1:6]
i.male.s2 <- dat2[[1]][7:12]
i.fem.s3 <- dat3[[1]][1:6]
i.male.s3 <- dat3[[1]][7:12]

i.fem.s1ept <- datept[[1]][1:6]
i.male.s1ept <- datept[[1]][7:12]
i.fem.s2ept <- dat2ept[[1]][1:6]
i.male.s2ept <- dat2ept[[1]][7:12]
i.fem.s3ept <- dat3ept[[1]][1:6]
i.male.s3ept <- dat3ept[[1]][7:12]

fems <- data.frame("M.F.Concurrency" = i.fem.s1, "Avg.Concurrency" = i.fem.s2, "No.Concurrency" = i.fem.s3)
fems2 <- data.frame("M.F.Concurrency" = i.fem.s1ept, "Avg.Concurrency" = i.fem.s2ept, "No.Concurrency" = i.fem.s3ept)

femFull <- rbind(fems, fems2)
femFull$AgeCat <- factor(rep(c("15-19", "20-24", "25-29", "30-34", "35-39", "40-44"),2))
femFull$Treatment <- c(rep("Low Partner Treatment", 6), rep("Increased Partner Treatment", 6))

femFull <- femFull %>% pivot_longer(cols=colnames(femFull)[1:3], names_to = "Behavior")

femFull %>% ggplot(aes(x=AgeCat, y=value, col=Treatment)) +
  geom_point() +
  facet_wrap("Behavior")
```

## Males
```{r incid-male}
males <- data.frame("M.F.Concurrency" = i.male.s1, "Avg.Concurrency" = i.male.s2, "No.Concurrency" = i.male.s3)
males2 <- data.frame("M.F.Concurrency" = i.male.s1ept, "Avg.Concurrency" = i.male.s2ept, "No.Concurrency" = i.male.s3ept)

maleFull <- rbind(males, males2)
maleFull$AgeCat <- factor(rep(c("15-19", "20-24", "25-29", "30-34", "35-39", "40-44"),2))
maleFull$Treatment <- c(rep("Low Partner Treatment", 6), rep("Increased Partner Treatment", 6))

maleFull <- maleFull %>% pivot_longer(cols=colnames(maleFull)[1:3], names_to = "Behavior")

maleFull %>% ggplot(aes(x=AgeCat, y=value, col=Treatment)) +
  geom_point() +
  facet_wrap("Behavior")
```
